### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [WhiskerzAB/PlaygroundTDD#6]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by gabrielPeart** [comment]
@lfarah Thank you for your feedback. We are already working on improvements and the `README.md` is already being improved as well.
